apiVersion: batch/v1
kind: CronJob
metadata:
  name: batch-worker
  namespace: playground
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: batch-worker
            image: asia-northeast1-docker.pkg.dev/playground-apps/samples/batch_worker:v1.0
          restartPolicy: Never
